In [15]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder

In [16]:
df = pd.read_csv("final_clean_data.csv")
df.head()

,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,OP_UNIQUE_CARRIER,ORIGIN,ORIGIN_STATE_ABR,DEST,DEST_STATE_ABR,CRS_DEP_TIME,DEP_DELAY,...,DEP_DELAY_GROUP,CRS_ARR_TIME,CRS_ELAPSED_TIME,DISTANCE,DISTANCE_GROUP,HourlyDewPointTemperature,HourlyDryBulbTemperature,HourlyRelativeHumidity,HourlyVisibility,HourlyWindSpeed
0,4,1,2,AA,GEG,WA,PHX,AZ,6.53,-5.0,...,-1.0,9.33,168.0,1020.0,5,33.0,36.0,89.0,5.0,10.0
1,4,1,2,AA,GEG,WA,PHX,AZ,15.45,15.0,...,1.0,18.12,160.0,1020.0,5,33.0,45.0,63.0,10.0,10.0
2,4,1,2,AA,SEA,WA,CLT,NC,7.33,-3.0,...,-1.0,15.32,299.0,2279.0,10,37.0,43.0,80.0,10.0,6.0
3,4,1,2,AA,SEA,WA,CLT,NC,13.83,-3.0,...,-1.0,21.83,300.0,2279.0,10,41.0,49.0,74.0,10.0,6.0
4,4,1,2,AA,SEA,WA,CLT,NC,22.00,-6.0,...,-1.0,6.00,300.0,2279.0,10,41.0,45.0,86.0,10.0,7.0

In [17]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50029 entries, 0 to 50028
Data columns (total 22 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   MONTH                      50029 non-null  int64
 1   DAY_OF_MONTH               50029 non-null  int64
 2   DAY_OF_WEEK                50029 non-null  int64
 3   OP_UNIQUE_CARRIER          50029 non-null  object
 4   ORIGIN                     50029 non-null  object
 5   ORIGIN_STATE_ABR           50029 non-null  object
 6   DEST                       50029 non-null  object
 7   DEST_STATE_ABR             50029 non-null  object
 8   CRS_DEP_TIME               50029 non-null  float64
 9   DEP_DELAY                  50029 non-null  float64
 10  DEP_DELAY_NEW              50029 non-null  float64
 11  DEP_DEL15                  50029 non-null  float64
 12  DEP_DELAY_GROUP            50029 non-null  float64
 13  CRS_ARR_TIME               50029 non-null  float64
 14  CRS_ELAPSED_TIME           50029 non-null  float64
 15  DISTANCE                   50029 non-null  float64
 16  DISTANCE_GROUP             50029 non-null  int64
 17  HourlyDewPointTemperature  50029 non-null  float64
 18  HourlyDryBulbTemperature   50029 non-null  float64
 19  HourlyRelativeHumidity     50029 non-null  float64
 20  HourlyVisibility           50029 non-null  float64
 21  HourlyWindSpeed            50029 non-null  float64
dtypes: float64(13), int64(4), object(5)
memory usage: 8.4+ MB

,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,CRS_DEP_TIME,DEP_DELAY,DEP_DELAY_NEW,DEP_DEL15,DEP_DELAY_GROUP,CRS_ARR_TIME,CRS_ELAPSED_TIME,DISTANCE,DISTANCE_GROUP,HourlyDewPointTemperature,HourlyDryBulbTemperature,HourlyRelativeHumidity,HourlyVisibility,HourlyWindSpeed
count,50029.000000,50029.000000,50029.000000,50029.000000,50029.000000,50029.000000,50029.000000,50029.000000,50029.000000,50029.000000,50029.000000,50029.000000,50029.000000,50029.000000,50029.000000,50029.000000,50029.000000
mean,5.068340,15.896520,3.984789,13.751268,8.444622,11.938076,0.203402,-0.001279,15.247840,184.196346,1183.186432,5.130944,42.884387,59.650723,57.524376,9.813888,8.271882
std,0.810098,8.745399,2.006712,5.267118,37.886269,36.559018,0.402533,1.920139,5.616437,84.851524,734.187641,2.962038,6.728408,9.344838,18.544547,0.974003,3.858438
min,4.000000,1.000000,1.000000,0.080000,-27.000000,0.000000,0.000000,-2.000000,0.020000,49.000000,93.000000,1.000000,5.000000,30.000000,11.000000,0.000000,0.000000
25%,4.000000,8.000000,2.000000,9.480000,-6.000000,0.000000,0.000000,-1.000000,11.230000,126.000000,679.000000,3.000000,39.000000,53.000000,43.000000,10.000000,6.000000
50%,5.000000,16.000000,4.000000,13.420000,-2.000000,0.000000,0.000000,-1.000000,15.880000,166.000000,987.000000,4.000000,43.000000,58.000000,58.000000,10.000000,8.000000
75%,6.000000,23.000000,6.000000,17.980000,9.000000,9.000000,0.000000,0.000000,19.480000,244.000000,1721.000000,7.000000,48.000000,65.000000,71.000000,10.000000,10.000000
max,6.000000,31.000000,7.000000,23.980000,1516.000000,1516.000000,1.000000,12.000000,23.980000,612.000000,2724.000000,11.000000,60.000000,102.000000,100.000000,10.000000,30.000000

In [18]:
df.isnull().sum()

MONTH                        0
DAY_OF_MONTH                 0
DAY_OF_WEEK                  0
OP_UNIQUE_CARRIER            0
ORIGIN                       0
ORIGIN_STATE_ABR             0
DEST                         0
DEST_STATE_ABR               0
CRS_DEP_TIME                 0
DEP_DELAY                    0
DEP_DELAY_NEW                0
DEP_DEL15                    0
DEP_DELAY_GROUP              0
CRS_ARR_TIME                 0
CRS_ELAPSED_TIME             0
DISTANCE                     0
DISTANCE_GROUP               0
HourlyDewPointTemperature    0
HourlyDryBulbTemperature     0
HourlyRelativeHumidity       0
HourlyVisibility             0
HourlyWindSpeed              0
dtype: int64

In [19]:
keep_cols = [
    "MONTH", "DAY_OF_MONTH", "DAY_OF_WEEK",
    "CRS_DEP_TIME", "CRS_ELAPSED_TIME",
    "OP_UNIQUE_CARRIER", "ORIGIN", "DEST",
    "DISTANCE",
    "HourlyDewPointTemperature", "HourlyDryBulbTemperature",
    "HourlyRelativeHumidity", "HourlyVisibility", "HourlyWindSpeed",
    "DEP_DELAY"
]

flight_dep_model = df[keep_cols].copy()
print("✅ Dataset cho mô hình delay cất cánh:", flight_dep_model.shape)
flight_dep_model.head(5)

✅ Dataset cho mô hình delay cất cánh: (50029, 15)

,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,CRS_DEP_TIME,CRS_ELAPSED_TIME,OP_UNIQUE_CARRIER,ORIGIN,DEST,DISTANCE,HourlyDewPointTemperature,HourlyDryBulbTemperature,HourlyRelativeHumidity,HourlyVisibility,HourlyWindSpeed,DEP_DELAY
0,4,1,2,6.53,168.0,AA,GEG,PHX,1020.0,33.0,36.0,89.0,5.0,10.0,-5.0
1,4,1,2,15.45,160.0,AA,GEG,PHX,1020.0,33.0,45.0,63.0,10.0,10.0,15.0
2,4,1,2,7.33,299.0,AA,SEA,CLT,2279.0,37.0,43.0,80.0,10.0,6.0,-3.0
3,4,1,2,13.83,300.0,AA,SEA,CLT,2279.0,41.0,49.0,74.0,10.0,6.0,-3.0
4,4,1,2,22.00,300.0,AA,SEA,CLT,2279.0,41.0,45.0,86.0,10.0,7.0,-6.0

### Encode CRS_DEP_TIME thành sin/cos (chu kỳ 24h)

In [20]:
import numpy as np

# --- CRS_DEP_TIME đã ở dạng float, ví dụ: 6.5 = 6h30, 13.75 = 13h45 ---

# Encode cyclical (chu kỳ 24h)
flight_dep_model["DEP_HOUR_sin"] = np.sin(2 * np.pi * flight_dep_model["CRS_DEP_TIME"] / 24)
flight_dep_model["DEP_HOUR_cos"] = np.cos(2 * np.pi * flight_dep_model["CRS_DEP_TIME"] / 24)

# (Tùy chọn) Bỏ cột gốc nếu không dùng nữa
# flight_dep_model.drop(columns=["CRS_DEP_TIME"], inplace=True)

# Kiểm tra vài dòng đầu
print(flight_dep_model[["CRS_DEP_TIME", "DEP_HOUR_sin", "DEP_HOUR_cos"]].head(10))

   CRS_DEP_TIME  DEP_HOUR_sin  DEP_HOUR_cos
0          6.53      0.990389     -0.138309
1         15.45     -0.785317     -0.619094
2          7.33      0.939991     -0.341200
3         13.83     -0.460974     -0.887413
4         22.00     -0.500000      0.866025
5          0.98      0.253758      0.967268
6          5.37      0.986429      0.164187
7          7.00      0.965926     -0.258819
8         10.68      0.338738     -0.940881
9         11.92      0.020942     -0.999781

In [21]:
# --- 3️⃣ Xác định categorical và numeric features ---
categorical_cols = ["MONTH", "DAY_OF_WEEK", "OP_UNIQUE_CARRIER", "ORIGIN", "DEST"]

numeric_cols = [
    "DAY_OF_MONTH", "CRS_ELAPSED_TIME", "DISTANCE",
    "HourlyDewPointTemperature", "HourlyDryBulbTemperature",
    "HourlyRelativeHumidity", "HourlyVisibility", "HourlyWindSpeed",
    "DEP_HOUR_sin", "DEP_HOUR_cos"
]

### Encoded cho phần linear, NN, ...

##### Encoded 5 features categorical bằng one-hot

In [22]:
# --- 4️⃣ One-Hot Encode bằng sklearn ---
ohe = OneHotEncoder(
    sparse_output=False,   # Xuất DataFrame dạng đầy đủ thay vì ma trận thưa
    drop=None,             # Giữ tất cả các cột (không drop_first)
    handle_unknown="ignore"  # Bỏ qua category mới trong tập test
)

# Fit và transform categorical features
encoded_array = ohe.fit_transform(flight_dep_model[categorical_cols])

# Lấy tên cột mới
encoded_cols = ohe.get_feature_names_out(categorical_cols)

# Tạo DataFrame chứa các cột one-hot
encoded_df = pd.DataFrame(encoded_array, columns=encoded_cols, index=flight_dep_model.index)


# --- 5️⃣ Gộp numeric + one-hot + target ---
flight_dep_onehot = pd.concat(
    [flight_dep_model[numeric_cols], encoded_df, flight_dep_model[["DEP_DELAY"]]],
    axis=1
)

# --- 6️⃣ Kiểm tra kết quả ---
print("\n✅ Dataset sau One-Hot Encoding:")
print("Số dòng:", flight_dep_onehot.shape[0])
print("Số cột:", flight_dep_onehot.shape[1])

# Hiển thị vài cột mới để kiểm tra
print("\n🧱 Một vài cột mới được tạo:")
print(flight_dep_onehot[encoded_cols[:10]].head(3))

# --- 7️⃣ (Tùy chọn) Lưu dataset đã encode để dùng cho Linear/NN ---
flight_dep_onehot.to_csv("flight_dep_linear.csv", index=False)

✅ Dataset sau One-Hot Encoding:
Số dòng: 50029
Số cột: 124

🧱 Một vài cột mới được tạo:
   MONTH_4  MONTH_5  MONTH_6  DAY_OF_WEEK_1  DAY_OF_WEEK_2  DAY_OF_WEEK_3  \
0      1.0      0.0      0.0            0.0            1.0            0.0
1      1.0      0.0      0.0            0.0            1.0            0.0
2      1.0      0.0      0.0            0.0            1.0            0.0

   DAY_OF_WEEK_4  DAY_OF_WEEK_5  DAY_OF_WEEK_6  DAY_OF_WEEK_7
0            0.0            0.0            0.0            0.0
1            0.0            0.0            0.0            0.0
2            0.0            0.0            0.0            0.0

### Encode cho phần Tree-based (RF, XGB, LGBM)

#### Label encoded cho OP_UNIQUE_CARRIER, ORIGIN, DEST
#### Còn MONTH, DAY_OF_WEEK ordinal encoded (vẫn như vậy)

In [23]:
label_cols = ["OP_UNIQUE_CARRIER", "ORIGIN", "DEST"]
label_encoders = {}

for col in label_cols:
    le = LabelEncoder()
    flight_dep_model[col] = le.fit_transform(flight_dep_model[col])
    label_encoders[col] = le
    print(f"🔤 {col}: {len(le.classes_)} categories encoded.")


# --- 4️⃣ Giữ lại các cột numeric + target ---
tree_ready_cols = [
    "MONTH", "DAY_OF_MONTH", "DAY_OF_WEEK",
    "CRS_ELAPSED_TIME", "DISTANCE",
    "HourlyDewPointTemperature", "HourlyDryBulbTemperature",
    "HourlyRelativeHumidity", "HourlyVisibility", "HourlyWindSpeed",
    "DEP_HOUR_sin", "DEP_HOUR_cos",
    "OP_UNIQUE_CARRIER", "ORIGIN", "DEST",
    "DEP_DELAY"
]

flight_dep_tree = flight_dep_model[tree_ready_cols]


# --- 5️⃣ Kiểm tra tổng quan ---
print("\n✅ Dataset sau khi encode:")
print("Số dòng:", flight_dep_tree.shape[0])
print("Số cột:", flight_dep_tree.shape[1])
print("\n📊 Kiểu dữ liệu:")
print(flight_dep_tree.dtypes.value_counts())

print("\n🔍 Xem vài dòng đầu:")
print(flight_dep_tree.head(5))


# --- 6️⃣ (Tùy chọn) Lưu lại để train model ---
flight_dep_tree.to_csv("flight_dep_tree.csv", index=False)

🔤 OP_UNIQUE_CARRIER: 12 categories encoded.
🔤 ORIGIN: 5 categories encoded.
🔤 DEST: 86 categories encoded.

✅ Dataset sau khi encode:
Số dòng: 50029
Số cột: 16

📊 Kiểu dữ liệu:
float64    10
int64       6
Name: count, dtype: int64

🔍 Xem vài dòng đầu:
   MONTH  DAY_OF_MONTH  DAY_OF_WEEK  CRS_ELAPSED_TIME  DISTANCE  \
0      4             1            2             168.0    1020.0
1      4             1            2             160.0    1020.0
2      4             1            2             299.0    2279.0
3      4             1            2             300.0    2279.0
4      4             1            2             300.0    2279.0

   HourlyDewPointTemperature  HourlyDryBulbTemperature  \
0                       33.0                      36.0
1                       33.0                      45.0
2                       37.0                      43.0
3                       41.0                      49.0
4                       41.0                      45.0

   HourlyRelativeHumidity  HourlyVisibility  HourlyWindSpeed  DEP_HOUR_sin  \
0                    89.0               5.0             10.0      0.990389
1                    63.0              10.0             10.0     -0.785317
2                    80.0              10.0              6.0      0.939991
3                    74.0              10.0              6.0     -0.460974
4                    86.0              10.0              7.0     -0.500000

   DEP_HOUR_cos  OP_UNIQUE_CARRIER  ORIGIN  DEST  DEP_DELAY
0     -0.138309                  0       1    62       -5.0
1     -0.619094                  0       1    62       15.0
2     -0.341200                  0       4    14       -3.0
3     -0.887413                  0       4    14       -3.0
4      0.866025                  0       4    14       -6.0

### ⚖️ Scale numeric features (DISTANCE, CRS_ELAPSED_TIME, weather)	
### ✂️ Train-test split, kiểm tra outlier của DEP_DELAY
#### 2 phần này sẽ làm sau do làm nhiều model